---
title: "data_processing"
output: html_document
date: "2023-09-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
```


```{r}
count_data = read.csv("/Users/justinli/Desktop/Shiny_App_Zhirui/more_datasets/rna_counts_batch_1_2.csv", header = TRUE)
head(count_data)
```



```{r}
sample_data <- read.table("/Users/justinli/Desktop/Shiny_App_Zhirui/more_datasets/all_samples.txt", header = TRUE)
head(sample_data)
```


```{r}
sub_sample = sample_data[1:54,]
dim(sub_sample)
head(sub_sample)
tail(sub_sample)
```

```{r}
sub_sample$rna_counts_matrix <- sub(".*/", "", sub_sample$rna_counts_matrix)
sub_sample = sub_sample[,-c(2,4,5)]
head(sub_sample)
```

```{r}
sub_sample <- sub_sample %>%
  select(names(sub_sample)[1], "experiment", names(sub_sample)[!names(sub_sample) %in% c(names(sub_sample)[1], "experiment")]) %>%
  rename(Treatment = treatment,
         Condition = condition,
         DaysPostInfection = dpi)
head(sub_sample)
```


```{r}
sub_count = count_data[,c(1:56)]
sub_count = sub_count[,-2]
colnames(sub_count)[2:ncol(sub_count)] = sub_sample$rna_counts_matrix
dim(sub_count)
head(sub_count)
```

```{r}
write.table(sub_sample, file = "sub_sample.txt", sep = "\t", row.names = FALSE, quote = FALSE)
write.table(sub_count, file = "sub_count.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```






